# CMake generated Testfile for 
# Source directory: /home/runner/work/wildfire_levelset/wildfire_levelset/regtest
# Build directory: /home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[basic_levelset]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/basic_levelset/inputs.i")
set_tests_properties([=[basic_levelset]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/basic_levelset" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;24;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;94;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[farsite_ellipse]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/farsite_ellipse/inputs.i")
set_tests_properties([=[farsite_ellipse]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/farsite_ellipse" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;24;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;95;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[rothermel_fuel]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/rothermel_fuel/inputs.i")
set_tests_properties([=[rothermel_fuel]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/rothermel_fuel" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;24;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;96;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[anderson_lw]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/anderson_lw/inputs.i")
set_tests_properties([=[anderson_lw]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/anderson_lw" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;24;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;97;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[terrain_wind]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/terrain_wind/inputs.i")
set_tests_properties([=[terrain_wind]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/terrain_wind" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;24;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;115;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[time_dependent_wind]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/time_dependent_wind/inputs.i")
set_tests_properties([=[time_dependent_wind]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/time_dependent_wind" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;24;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;116;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[landfire_farsite_setup]=] "/usr/bin/python3.12" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/landfire_farsite/create_landscape.py")
set_tests_properties([=[landfire_farsite_setup]=] PROPERTIES  FIXTURES_SETUP "landfire_farsite_fixture" LABELS "regtest" TIMEOUT "300" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/landfire_farsite" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;70;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;121;add_python_setup_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[landfire_farsite]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/landfire_farsite/inputs.i")
set_tests_properties([=[landfire_farsite]=] PROPERTIES  FIXTURES_REQUIRED "landfire_farsite_fixture" LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_check/regtest/landfire_farsite" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;80;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;121;add_python_setup_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
