#!/usr/bin/env python3
"""
create_landscape.py - Generate the landscape file for the landfire_farsite regtest.

This script first attempts to download LANDFIRE data for a small Southern
California extent using the LANDFIRE Product Service (LFPS) API.  If the
download fails (no internet connectivity, API unavailable, or missing
dependencies), it falls back to generating a synthetic landscape that is
representative of chaparral terrain and writes it to the same output path so
that the regression test can always proceed.

Usage (called by CMake/CTest):
  python3 create_landscape.py [--output landscape.lcp] [--subsample N]

The default output filename is ``landscape.lcp`` in the current working
directory.
"""

import argparse
import math
import os
import sys

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Small Southern California extent (near the Santa Monica Mountains)
_DEFAULT_BBOX = (-118.85, 34.10, -118.75, 34.18)  # (min_lon, min_lat, max_lon, max_lat)

# LANDFIRE vintage to use
_VINTAGE = 2020

# Subsample factor when downloading (keeps data manageable for a regtest)
_DEFAULT_SUBSAMPLE = 10

# Synthetic landscape parameters (fallback)
_SYNTH_NX      = 11   # number of grid points in x
_SYNTH_NY      = 11   # number of grid points in y
_SYNTH_SPACING = 30.0  # metres between points


# ---------------------------------------------------------------------------
# Synthetic landscape generator (no external dependencies)
# ---------------------------------------------------------------------------

def _generate_synthetic_landscape(output_path, nx=_SYNTH_NX, ny=_SYNTH_NY,
                                   spacing=_SYNTH_SPACING):
    """Write a synthetic Southern California chaparral landscape file.

    The landscape mimics a gentle hillslope:
    - Elevation increases from SW to NE
    - Slope 10-25 degrees (typical chaparral foothills)
    - Aspect predominantly SW-facing (225 degrees, fire-prone orientation)
    - Fuel model FM4 (chaparral) throughout

    Parameters
    ----------
    output_path : str
        Destination .lcp file path.
    nx, ny : int
        Grid dimensions.
    spacing : float
        Grid spacing in metres.
    """
    x_orig = 0.0
    y_orig = 0.0

    rows = []
    for j in range(ny):
        for i in range(nx):
            x = x_orig + i * spacing
            y = y_orig + j * spacing

            # Elevation: gentle NE-rising gradient, 100-200 m range
            norm_x = i / max(nx - 1, 1)
            norm_y = j / max(ny - 1, 1)
            elev = 100.0 + 100.0 * (0.4 * norm_x + 0.6 * norm_y)

            # Slope: 10-25 degrees, slightly higher near centre
            dist_centre = math.sqrt((norm_x - 0.5)**2 + (norm_y - 0.5)**2)
            slope = 10.0 + 15.0 * (1.0 - dist_centre * 2.0)
            slope = max(5.0, min(35.0, slope))

            # Aspect: predominantly SW-facing with slight variation
            aspect = 225.0 + 20.0 * math.sin(math.pi * norm_x) * math.cos(math.pi * norm_y)
            aspect = aspect % 360.0

            # Fuel: FM4 (chaparral) throughout
            fuel = 4

            rows.append((x, y, elev, slope, aspect, fuel))

    with open(output_path, "w") as fh:
        fh.write(
            "# Synthetic landscape generated by create_landscape.py\n"
            "# (LANDFIRE download unavailable; using fallback synthetic data)\n"
            "# Format: X Y ELEVATION SLOPE ASPECT FUEL_MODEL\n"
            f"# Grid: {nx}x{ny} points at {spacing}m spacing\n"
            "# Terrain: Southern California chaparral hillslope (synthetic)\n"
        )
        for (x, y, elev, slope, aspect, fuel) in rows:
            fh.write(f"{x:.2f} {y:.2f} {elev:.2f} {slope:.2f} {aspect:.2f} {fuel}\n")

    print(f"Generated synthetic landscape ({nx}x{ny} = {len(rows)} points) "
          f"→ '{output_path}'")


# ---------------------------------------------------------------------------
# LANDFIRE download attempt
# ---------------------------------------------------------------------------

def _try_download_landscape(output_path, bbox, subsample, timeout_s=120):
    """Attempt to download a LANDFIRE landscape.  Returns True on success."""
    # Add tools directory to path so we can import landfire_to_lcp
    _this_dir = os.path.dirname(os.path.abspath(__file__))
    _repo_root = os.path.abspath(os.path.join(_this_dir, "..", ".."))
    _tools_dir = os.path.join(_repo_root, "tools")
    if _tools_dir not in sys.path:
        sys.path.insert(0, _tools_dir)

    # Dependency checks
    try:
        import requests  # noqa: F401
    except ImportError:
        print("INFO: 'requests' not installed – skipping LANDFIRE download.")
        return False
    try:
        import rasterio  # noqa: F401
    except ImportError:
        print("INFO: 'rasterio' not installed – skipping LANDFIRE download.")
        return False

    try:
        import landfire_to_lcp as lfp
        print(f"Attempting LANDFIRE download for bbox {bbox} …")
        lfp.create_landscape(
            output_path,
            bbox=bbox,
            vintage=_VINTAGE,
            project_utm=True,
            subsample=subsample,
            keep_nonburnable=False,
            timeout_s=timeout_s,
        )
        return True
    except Exception as exc:
        print(f"INFO: LANDFIRE download failed ({exc}); using synthetic fallback.")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", default="landscape.lcp",
        help="Output landscape file path (default: landscape.lcp)",
    )
    parser.add_argument(
        "--subsample", type=int, default=_DEFAULT_SUBSAMPLE,
        help=f"Subsample factor for LANDFIRE download (default: {_DEFAULT_SUBSAMPLE})",
    )
    parser.add_argument(
        "--timeout", type=int, default=120,
        help="LANDFIRE API timeout in seconds (default: 120)",
    )
    parser.add_argument(
        "--bbox", nargs=4, type=float,
        metavar=("MIN_LON", "MIN_LAT", "MAX_LON", "MAX_LAT"),
        default=list(_DEFAULT_BBOX),
        help=(
            "Bounding box in WGS-84 decimal degrees "
            f"(default: {_DEFAULT_BBOX})"
        ),
    )
    args = parser.parse_args(argv)

    # Ensure the output directory exists
    out_dir = os.path.dirname(os.path.abspath(args.output))
    os.makedirs(out_dir, exist_ok=True)

    bbox = tuple(args.bbox)
    success = _try_download_landscape(
        args.output, bbox=bbox, subsample=args.subsample, timeout_s=args.timeout
    )

    if not success:
        _generate_synthetic_landscape(args.output)

    if not os.path.isfile(args.output):
        print(f"ERROR: landscape file was not created: {args.output}",
              file=sys.stderr)
        sys.exit(1)

    # Report row count
    with open(args.output) as fh:
        n = sum(1 for l in fh if not l.startswith("#") and l.strip())
    print(f"Landscape file ready: '{args.output}' ({n} data rows)")


if __name__ == "__main__":
    main()
