# CMake generated Testfile for 
# Source directory: /home/runner/work/wildfire_levelset/wildfire_levelset/regtest
# Build directory: /home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/regtest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[basic_levelset]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/basic_levelset/inputs.i")
set_tests_properties([=[basic_levelset]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/regtest/basic_levelset" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;21;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;44;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[farsite_ellipse]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/farsite_ellipse/inputs.i")
set_tests_properties([=[farsite_ellipse]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/regtest/farsite_ellipse" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;21;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;45;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[rothermel_fuel]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/rothermel_fuel/inputs.i")
set_tests_properties([=[rothermel_fuel]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/regtest/rothermel_fuel" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;21;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;46;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[anderson_lw]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/anderson_lw/inputs.i")
set_tests_properties([=[anderson_lw]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/regtest/anderson_lw" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;21;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;47;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
add_test([=[terrain_wind]=] "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/levelset" "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/terrain_wind/inputs.i")
set_tests_properties([=[terrain_wind]=] PROPERTIES  LABELS "regtest" TIMEOUT "600" WORKING_DIRECTORY "/home/runner/work/wildfire_levelset/wildfire_levelset/build_warn/regtest/terrain_wind" _BACKTRACE_TRIPLES "/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;21;add_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;65;add_regression_test;/home/runner/work/wildfire_levelset/wildfire_levelset/regtest/CMakeLists.txt;0;")
